name: Template action
description: Template action description

inputs:
  packageFile:
    required: true
    default: 'package.json'
    description: Relative to workspace path to package manifest file

outputs:
  version:
    description: Full package version
  patchVersion:
    description: Patch package version with prerelease info (e.g. 1.2.3, 1.2.3-alpha)
  minorVersion:
    description: Minor package version with prerelease info (e.g. 1.2, 1.2-alpha)
  majorVersion:
    description: Major package version with prerelease info (e.g. 1, 1-alpha)

runs:
  using: node12
  main: 'dist/index.js'
